guardian/atom-renderer

package.json, src/main/resources/css/atoms/_snippet.scss, src/main/resources/fragments/atoms/snippetImage.scala.html, src/main/resources/guide/article/index.scala.html
As reported by Ben. I also simplified the markup for images as there wasn't any need for a wrapping `DIV` #detailsmatter.
=> Fix a few snippet visual bugs

src/main/scala/AtomRenderer.scala, src/main/scala/Configuration.scala
Seed for customizing atom rendering. No configuration is being used right now but ultimately each atom type will have its own specific configuration class (so that the type system helps us prevent missing data) and the overloaded methods I added will be removed.
This will become helpful for a list of scenarios, for instance:
- interacting with 3rd party services, like imgIX to generate optimized responsive images in a secure setting
- sharing properties that should remain hidden from the outside world, like private URLs, passwords, etc.
- provide platform-specific rendering without any form of complecting
=> Add configuration

src/main/resources/css/atoms/_snippet.scss, src/main/resources/css/helpers/_multiline.scss, src/main/resources/storyquestions/article/index.scss
Safari needs extra care with borders: `border-image` works correctly only when the `border-color` is not transparent, and one should make sure the `border-width`s are explicitly set.
Also reverting the renaming of 'arts' into 'culture' as even thought the pillar was renamed, its label is _still_ the same _but_ the SASS var in frontend _has been_ renamed, and this is where I got lost 😲 
Checked with apps: both frontend and apps will identify the culture pillar as arts.
=> Fix multine border on Safari

src/main/resources/explainer/article/index.scala.html, src/main/resources/explainer/article/index.scss
In order to support explainers in old articles, we want this library to be able to render them.
This adds the CSS and Html templates to render them. 
A separate pull request in CAPI will change the html to use the `gu-tools` format and not the interactive one. 
NB: We are stripping the feedback buttons out. 
[Article with an explainer example](https://www.theguardian.com/world/2017/sep/05/azerbaijani-laundromat-shows-how-regime-robs-its-people-to-feed-itself)
[Trello ticket](https://trello.com/c/Qa9XYPhG/173-kill-the-old-explainer-part-2)
=> Explainer: Add code for rendering explainers 

package.json, src/main/resources/__flow__/types/atoms.fjs, webpack/atomTypes.js
We need to add the 'explainer' atom to the list of types exported by Atom Renderer.
=> Fix: add atom type explainer

src/main/resources/css/_vars.scss, src/main/resources/css/atoms/_snippet.scss, src/main/resources/storyquestions/article/index.scss
Until the apps have done the CSS var substitution for pillar colours, we encode them in our local vars. This to prevent display bugs, esp. with buttons, in android and ios.
=> Add SASS vars for pillar colours

package.json, src/main/resources/explainer/article/index.fjs, src/main/resources/explainer/article/index.scss
The Default export for the JS needs to be mocked out 
The CSS classes were wrong
=> Fix Explainer CSS & default JS export 

build.sbt, src/main/scala/AtomRenderer.scala, src/main/scala/json/package.scala
This must be provided by the end-user.
=> Remove JSON logic

core/src/main/scala/renderers/email/Hydrator.scala, utils/src/main/scala/com.gu.contentatom.renderer/utils/CapiRenderer.scala
ExactTarget expects the payload of an HTML email to be whatever is inside the `body` element. Previously the atom renderer was sending a complete HTML document, this change addresses that.
=> Fix for ExactTarget

core/src/main/scala/renderers/email/Hydrator.scala
Exact Target expects fully-formed XML, but the atom renderer produces HTML. Fortunately, JSOUP provides the ability to choose the syntax of the output. This changes makes sure whatever is output by the email renderer will be XML-compliant.
=> Update document output settings to produce XML

core/src/main/resources/profile/email/index.scala.html, core/src/main/resources/qanda/email/index.scala.html, core/src/main/resources/timeline/email/index.scala.html
In email, all snippets must be wrapped inside a master table that sets the general layout of the email.
(I surrounded each fragment by `fragment.email(atom)`, is all)
=> Fix: Surround each snippet with email skeleton

core/src/main/resources/commonsdivision/article/index.scss, core/src/main/resources/css/_vars.scss, core/src/main/resources/css/atoms/_snippet.scss, core/src/main/resources/css/email/snippets.scss, core/src/main/resources/storyquestions/article/index.scss
As a design principle, the atom library should hold off as few information as possible and delegate any choice over to the platform. This is exactly the same reasoning as with polymorphism vs monomorphism, i.e. by making a function more polymorphic, we restrict the things it can do with its argument.
In this example, we require the host platform to provide colour information, as these things usually are tweaked locally to accommodate software or hardware specifications. (Ultimately, we don't want _any_ SASS variable that might otherwise be provided by the platform)
=> Pillar color provided by platform

core/src/main/scala/renderers/email/Hydrator.scala
An XML processor does not understand named entity references like `&nbsp;` if they are not defined first. That alone is a whole conundrum, but fortunately there's an easy way around it: use entity references instead, i.e. `&#x00A0;`, and jsoup provides a nice API to take care of this for us.
=> Encode HTML entities in XML

core/src/main/resources/css/email/snippets.scss, core/src/main/resources/fragments/email/snippet.scala.html, core/src/main/resources/guide/email/index.scala.html, core/src/main/resources/profile/email/index.scala.html, core/src/main/resources/qanda/email/index.scala.html
Based on visual feedback, two things need fixing:
1- there is a missing 1px rule between the introductory paragraph and the content of the snippet
2- the image must be aligned with the top of the text
=> Snippet email fixes

core/src/main/resources/commonsdivision/article/index.scala.html, core/src/main/resources/commonsdivision/article/index.scss, core/src/main/scala/Configuration.scala, utils/src/main/scala/com.gu.contentatom.renderer/utils/CapiRenderer.scala
- Overrides some border styling in the app
- Adds a flag to disable the rendering of MP lists. This doesn't work properly on the app, and needs a better solution. For now we'll just hide it.
=> Commonsdivision atom - fix app style and make MP lists optional

package.json, webpack/css.js, yarn.lock
_This is a frontend-only change, as apps do not need the following trick._
With this change, we are not inlining values for CSS vars anymore, and instead expect frontend to provide CSS vars for us. This change is motivated by two things
1. There is a great support for CSS vars across desktop browsers
... we can live with the fact that IE users won't see pillar colours.
2. We used to know how many pillars there is and had variables for each one, but that is an information leak from the underlying platform. Atom-renderer should know nothing except for what is contextually relevant; i.e. it should only know about the "current" pillar colour, the others don't matter. In practice, it translates to moving from
```css
/* leak: .pillar--XYZ class names are defined in frontend */
.pillar--news …
```
=> Remove CSS vars swap trickery

core/src/main/scala/renderers/email/Hydrator.scala
JSOUP provides a nice API to make sure the HTML that comes in is freed of anything we would not want such as attributes, elements, and even attribute values. In our use case, we need to add placeholders inside `href` attributes that ExactTarget can then substitute with a proper value, e.g. `<a href="%%unsubscribe%%">`. Sadly, these are not valid URLs and JSOUP will remove them during cleanup. As far as I know, there is no way to prevent that (I tried hacking the `withProtocols`).
We must then disable cleanup. It is not too bad, because this is first-party data and code we control end-to-end, it is unlikely there will ever be something wrong.
=> Hydrator: Do not clean the HTML input anymore

core/src/main/resources/commonsdivision/article/index.scss, core/src/main/resources/css/atoms/_snippet.scss, core/src/main/resources/css/email/snippets.scss, core/src/main/resources/storyquestions/article/index.scss
This is to fix a bug a few users reported, where the button "disappeared" after having interacted with it, while also providing a fallback value for user agents not supporting CSS variables.
=> Add fallback colour when missing vars

README.md
This is because we [sign releases](https://github.com/guardian/atom-renderer/blob/master/build.sbt#L71).
=> add note to install sbt-pgp plugin globally

core/src/main/resources/css/atoms/_audio.scss
Flexbox has more browser support in mobile, this is a defensive PR for devices running older OS versions. In a bare page, they render exactly the same, meaning all things being equal these changes are safe.
**Grid**
**Flexbox**
=> Use flexbox for inline player

core/src/main/resources/__flow__/types/ophan.fjs, core/src/main/resources/audio/article/index.scala.html, core/src/main/resources/lib/audio.fjs, core/src/main/resources/lib/ophan.fjs, core/src/main/scala/Configuration.scala, package.json, utils/src/main/scala/com.gu.contentatom.renderer/utils/CapiRenderer.scala
Summary of changes for the audio atom;
- Now emits the milestone events for 25, 50 and 75%, and THE_END during playback
- Can be instructed to provide ad-free or Acast-wrapped audio source URLs
- Responds to user interaction with the progress bar, playing from the time selected (see graphic)
**Note: this version still carries the DEV version number, so don't merge until that's updated with the latest released version!**
Screenshots;
(captured locally) - there's a long-ish delay at 00:07:07 when the audio is first played - this is currently a known issue with audio playback
=> Audio atom - add milestone events, time seeking and ad-free compatibility

core/src/main/resources/lib/audio.fjs, package.json
Testing of the code merged in https://github.com/guardian/atom-renderer/pull/58 had a few remaining bugs. These were:
- The PLAY ophan event was never sent
- The THE_END ophan event was sent too early when ads were present
- The UI did not update to reflect the completed status properly
- It was possible to trigger duplicated ophan events
Other changes:
- We're using simplified event listeners on elements for all the events we're interested in (for audio anyway). We've seen how the more complex implementation can upset Safari, so I think it's better to remove that possibility across the board.
- String literals representing playback milestones have been replaced with their `<Action>.<EVENT>` equivalents - to help prevent typing errors in future comparisons etc.
Outstanding issues:
- The …
=> Audio Atom: Simplify event listeners and fix some errors 

core/src/main/resources/__flow__/types/ophan.fjs, core/src/main/resources/lib/audio.fjs, core/src/main/resources/lib/ophan.fjs
Brief summary:
- we keep `ComponentEvent` and `MediaEvent` separate, as they are in the Thrift model
- the PAUSE event does not exist
- reduce the number of closures by binding the `Audio` object once
- clean up _everything_ on `stop` to avoid memory leaks
=> Few fixes in the audio atom JS

core/src/main/resources/chart/article/index.scala.html, core/src/main/scala/utils/RichImplicits.scala
Due to how chart atoms are currently working, we need to hack our way into the iframe resize algorithm. In order to do this, we must be able to (1) identify the iframe and (2) delay the resize event until after listeners have been registerd.
Point (1) is addressed by the `name` attribute. Point (2) is done by disabling all scripts in a crude way (replacing `script` with `gu-script` tags). On the platform size, event listeners are registers and then only is the `gu-script` -> `script` conversion done.
=> Add some markup for easy detection

core/src/main/resources/css/atoms/_audio.scss, core/src/main/resources/css/atoms/_snippet.scss, package.json
Adjust the label font weight up to 600 and the headline font weight down to 400 on audio and snippet atoms. See this [Trello card](https://trello.com/c/tSzKm3VM/626-audio-atom-and-snippet-atom-change-the-kicker-font-weight-to-600).
Initially I just adjusted the label font weight but that had a weird side effect of also making the headline font heavier too. For example;
**Original appearance (font weight 500 shared by both classes):**
**Interim appearance (label font weight 600, headline 500):**
**Final appearance (label font weight 600, headline weight dropped to 400):**
In all cases, the correct weight is shown in the dev tools for both elements, but the appearance was definitely different.
=> Adjust audio and snippet atom label and headline font weights

core/src/main/resources/css/atoms/_audio.scss, core/src/main/resources/lib/audio.fjs
First pass to update the play/pause button and the slider thumb control to use the pillar colour.
We still have to find a way to make the progress bar apply the correct colour (or choose a neutral one) for the 'played' section. It's set by javascript and currently hard-coded to match the news pillar.
**Before**
**After**
=> Apply pillar colour to audio controls

core/src/main/resources/css/atoms/_audio.scss, core/src/main/resources/lib/audio.fjs, package.json
Restores background gradient fill on progress bar for Firefox browsers.
**Before:**
**After:**
Also re-tested (locally) with Chrome and Safari and they're still ok.
=> Use Firefox-specific CSS to draw background-image gradient on progress bar

core/src/main/resources/__flow__/types/ophan.fjs, core/src/main/resources/lib/ophan.fjs, package.json
Ophan translates incoming media events from e.g. `audio:content:25` into the form it expects e.g. `audio:content:PERCENT25`. We were originally emitting the latter, post-translated form, which Ophan couldn't deal with properly.
Now we'll output the pre-translated values that it _can_ understand and should be able to translate properly, so we should begin to see progress updates passing through all the way to the data lake 🤞
=> Change MediaEvent values to match those expected by Ophan

core/src/main/resources/css/atoms/_buttons.scss, core/src/main/resources/fragments/atoms/snippet.scala.html
Clicks on `BUTTON` elements inside a `SUMMARY` will not propagate events such that the behaviour of the surrounding `DETAILS` is preserved, not in Firefox.
As a result, people have been complaining that they can't open snippets when they hit the "Show" button. To fix that, we use a simple `SPAN` instead.
=> Use SPAN for the show/hide element

package.json, webpack/css.js
Small breaking change in the latest version of `sass-loader`, because changing the name is _always a good idea_:tm:
=> Fix SASS loader config

package.json, version.sbt
I forgot to do this as part of https://github.com/guardian/atom-renderer/pull/77
=> Bump version number in package.json and version.sbt

core/src/main/scala/utils/RichImplicits.scala
The correct implementation of function `durationStr` is incorrect. 
(This was noticed by the fact that some videos on the site shows a sudden jump from the originally displayed time, which is the output of `durationStr`, to the correct time after one clicked on play. Example: https://www.theguardian.com/football/2020/jan/20/the-fiver-alan-pardew-chris-powell-den-haag-ghostbusters).
Starting with a duration of `3802` ( The duration carried by the AudioAtom on the above page ) the current implementation behave like this:
```
duration = 3802
seconds = duration % 60
minutes = [ 59, duration / 60 ].min
hours   = duration / 3600
(hours, minutes, seconds) -> (1,59,22) # Incorrect! 
```
The correct code proposed change, does this
```
duration = 3802
hours   = duration / 3600
minutes = ( duration …
```
=> Correct implementation of durationStr

core/src/main/resources/__flow__/types/global.fjs, core/src/main/resources/lib/audio.fjs, package.json, utils/src/main/twirl/com.gu.contentatom.renderer.utils/page.scala.html
...as clients calling this only have access to the value as a promise typically. (I.e. this is how the consent-management-platform library works.)
=> Change Acast consent type to Promise

core/src/main/resources/__flow__/types/global.fjs, core/src/main/resources/lib/audio.fjs, package.json, utils/src/main/twirl/com.gu.contentatom.renderer.utils/page.scala.html
Required as consent is not set once but can change multiple times on a single page. In fact, because of the way the consent library works this always happens.
=> Use callback for Acast (audio ads) consent
